### ISSUE TITLE
Reasons for dropping LiveData<Event<*>> and EventObserver pattern?

### ISSUE THREAD

**Issue by lucamtudor** [AdamSHurwitz/Coinverse#1]
I watched your SF presentation and I was wondering why you decided to stop using the EventObserver pattern?

**Comment by adam-hurwitz** [comment]
Great question @lucamtudor! Coinverse is in the process of a major refactor. I was experimenting with LiveData and seeing if the `Event` pattern was necessary. Coming soon is a Model-View-Intent (MVI) version utilizing Kotlin StateFlow. This new pattern will greatly reduce the usage of the Event pattern due to one view state being emitted at a time. However, some one-time events may still use the Event pattern wrapping a Kotlin Flow type instead of LiveData.

Stay tuned! In the meantime, you can explore my [notes on MVI](https://docs.google.com/document/d/13fmrGJbGHNEPo3FN7IDmwQjxjXK3qoACSRqjyawV32k/edit).
